"""
Standalone Interactive HTML Report Generator Module
Generates an all-in-one HTML dashboard report file for presentation and offline sharing.
"""
import os
import datetime
import pandas as pd
from typing import Dict, Any, List

def generate_interactive_html_report(
    primary_kw: str,
    keywords_list: List[str],
    stats_df: pd.DataFrame,
    channel_dfs: Dict[str, pd.DataFrame],
    ai_summaries: Dict[str, List[str]]
) -> str:
    """독립형 인터랙티브 HTML 보고서 파일 생성"""
    os.makedirs(os.path.join("output", "reports"), exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_kw = "".join(c for c in primary_kw if c.isalnum() or c in (" ", "_", "-")).strip().replace(" ", "_")
    report_file = os.path.join("output", "reports", f"briefing_report_{safe_kw}_{timestamp}.html")
    
    total_docs = stats_df["total_count"].sum() if not stats_df.empty else 0
    
    # HTML 조각 생성
    ai_cards_html = ""
    for ch_name, lines in ai_summaries.items():
        ai_cards_html += f"""
        <div style="background:#f8fafc; border:1px solid #cbd5e1; border-left:6px solid #3b82f6; border-radius:8px; padding:15px; margin-bottom:15px;">
            <h4 style="margin-top:0; color:#1e40af; margin-bottom:8px;">📌 [{ch_name}] AI 핵심 인사이트</h4>
            <div style="font-size:0.92rem; color:#334155; line-height:1.6;">
                {lines[0]}<br>
                {lines[1]}<br>
                {lines[2]}
            </div>
        </div>
        """
        
    stats_table_html = stats_df.to_html(classes="styled-table", index=False) if not stats_df.empty else "<p>통계 데이터 없음</p>"
    
    html_content = f"""<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>네이버 마켓 인사이트 분석 리포트 - {primary_kw}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Pretendard", "Segoe UI", sans-serif; line-height: 1.6; color: #1e293b; background: #f1f5f9; margin: 0; padding: 30px; }}
        .container {{ max-width: 1100px; margin: 0 auto; background: #ffffff; padding: 40px; border-radius: 16px; box-shadow: 0 10px 25px rgba(0,0,0,0.05); }}
        h1 {{ color: #0f172a; border-bottom: 3px solid #3b82f6; padding-bottom: 12px; margin-top: 0; }}
        .kpi-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin: 25px 0; }}
        .kpi-card {{ background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 18px; text-align: center; }}
        .kpi-value {{ font-size: 1.8rem; font-weight: 800; color: #2563eb; margin-top: 6px; }}
        .styled-table {{ width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 0.95rem; }}
        .styled-table th {{ background: #2563eb; color: #ffffff; text-align: left; padding: 12px; }}
        .styled-table td {{ padding: 10px 12px; border-bottom: 1px solid #e2e8f0; }}
        .styled-table tr:nth-child(even) {{ background: #f8fafc; }}
        .footer {{ text-align: center; font-size: 0.85rem; color: #94a3b8; margin-top: 40px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 네이버 마켓 인사이트 종합 브리핑 리포트</h1>
        <p><b>분석 대상 키워드:</b> {primary_kw} (비교: {', '.join(keywords_list)}) | <b>생성 일시:</b> {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        
        <div class="kpi-grid">
            <div class="kpi-card">
                <div style="font-size:0.85rem; color:#64748b;">8대 채널 누적 총 인덱스</div>
                <div class="kpi-value">{total_docs:,}건</div>
            </div>
            <div class="kpi-card">
                <div style="font-size:0.85rem; color:#64748b;">분석 키워드 수</div>
                <div class="kpi-value">{len(keywords_list)}개</div>
            </div>
            <div class="kpi-card">
                <div style="font-size:0.85rem; color:#64748b;">분석 채널 수</div>
                <div class="kpi-value">{len(channel_dfs)}대 채널</div>
            </div>
        </div>

        <h2 style="color:#1e293b; margin-top:35px;">🤖 채널별 AI 3줄 핵심 인사이트 브리핑</h2>
        {ai_cards_html}

        <h2 style="color:#1e293b; margin-top:35px;">📊 8대 채널 총 검색 문서수 통계</h2>
        {stats_table_html}

        <div class="footer">
            Generated by Naver Market Insight Intelligent Analytics Platform
        </div>
    </div>
</body>
</html>
"""
    with open(report_file, "w", encoding="utf-8") as f:
        f.write(html_content)
        
    return report_file
